TechBridge/core/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TechBridge/manager/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include('register.urls', namespace='register')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('', include('core.urls', namespace='core')),
]

TechBridge/projects/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'projects'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('requests', views.requests, name='requests'),
    path('new-project/', views.newProject, name='new-project'),
    path('new-project/<int:id>', views.newProjectFromRequest, name='new-project'),
    path('new-project-request/', views.newProjectRequest, name='new-project-request'),
    path('new-task/', views.newTask, name='new-task'),
]

TechBridge/projects/models.py
from django.db import models
from django.utils import timezone
from register.models import User, Member
from django.core.validators import MaxValueValidator, MinValueValidator

status = (
    ('1', 'Stuck'),
    ('2', 'Working'),
    ('3', 'Done'),
)

due = (
    ('1', 'On Due'),
    ('2', 'Overdue'),
    ('3', 'Done'),
)

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=80)
    slug = models.SlugField('shortcut', blank=True)
    efforts = models.DurationField()
    status = models.CharField(max_length=7, choices=status, default=1)
    complete_per = models.FloatField(default=0,max_length=2, validators = [MinValueValidator(0), MaxValueValidator(100)])
    description = models.TextField(blank=True)
    start_date = models.DateField(auto_now_add=True)
    upd_date = models.DateField(auto_now_add=False, auto_now=True)
    dead_line = models.DateField()
    github = models.URLField(blank=True)
    product_link = models.URLField(blank=True)
    requester = models.ForeignKey(User, on_delete=models.CASCADE, related_name="requested_project")
    developers = models.ManyToManyField(Member, related_name="developing_project")
    managers = models.ManyToManyField(Member, related_name="managing_project")

    class Meta:
        ordering = ['name']

    def __str__(self):
        return (self.name)
    
class ProjectRequest(models.Model):
    requester = models.ForeignKey(User, on_delete=models.CASCADE, related_name="requested_project_request")
    name = models.CharField(max_length=80)
    slug = models.SlugField('shortcut', blank=True)
    dead_line = models.DateField()
    description = models.TextField()
    started = models.BooleanField(default=False)
    class Meta:
        ordering = ['name']

    def __str__(self):
        return (self.name)


class Task(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    assign = models.ManyToManyField(Member)
    task_name = models.CharField(max_length=80)
    status = models.CharField(max_length=7, choices=status, default=1)
    due = models.CharField(max_length=7, choices=due, default=1)

    class Meta:
        ordering = ['project', 'task_name']

    def __str__(self):
        return(self.task_name)

TechBridge/projects/forms.py
from django import forms
from django.utils.text import slugify
from .models import Task
from .models import Project, ProjectRequest
from register.models import School, Member

status = (
    ('1', 'Stuck'),
    ('2', 'Working'),
    ('3', 'Done'),
)

due = (
    ('1', 'On Due'),
    ('2', 'Overdue'),
    ('3', 'Done'),
)


class TaskRegistrationForm(forms.ModelForm):
    project = forms.ModelChoiceField(queryset=Project.objects.all())
    assign = forms.ModelMultipleChoiceField(queryset=Member.objects.all())
    task_name = forms.CharField(max_length=80)
    status = forms.ChoiceField(choices=status)
    due = forms.ChoiceField(choices=due)

    class Meta:
        model = Task
        fields = '__all__'


    def save(self, commit=True):
        task = super(TaskRegistrationForm, self).save(commit=False)
        task.project = self.cleaned_data['project']
        task.task_name = self.cleaned_data['task_name']
        task.status = self.cleaned_data['status']
        task.due = self.cleaned_data['due']
        task.save()
        assigns = self.cleaned_data['assign']
        for assign in assigns:
            task.assign.add((assign))

        if commit:
            task.save()

        return task


    def __init__(self, *args, **kwargs):
        super(TaskRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['project'].widget.attrs['class'] = 'form-control'
        self.fields['project'].widget.attrs['placeholder'] = 'Social Name'
        self.fields['task_name'].widget.attrs['class'] = 'form-control'
        self.fields['task_name'].widget.attrs['placeholder'] = 'Name'
        self.fields['status'].widget.attrs['class'] = 'form-control'
        self.fields['status'].widget.attrs['placeholder'] = 'Email'
        self.fields['due'].widget.attrs['class'] = 'form-control'
        self.fields['due'].widget.attrs['placeholder'] = 'City'
        self.fields['assign'].widget.attrs['class'] = 'form-control'
        self.fields['assign'].widget.attrs['placeholder'] = 'Found date'


class ProjectRegistrationForm(forms.ModelForm):
    name = forms.CharField(max_length=80)
    # slug = forms.SlugField('shortcut')
    developers = forms.ModelMultipleChoiceField(queryset=Member.objects.all())
    managers = forms.ModelMultipleChoiceField(queryset=Member.objects.all())
    efforts = forms.DurationField()
    status = forms.ChoiceField(choices=status)
    dead_line = forms.DateField()
    # complete_per = forms.FloatField(min_value=0, max_value=100)
    description = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Project
        fields = '__all__'


    def save(self, commit=True):
        project = super(ProjectRegistrationForm, self).save(commit=False)
        project.name = self.cleaned_data['name']
        project.efforts = self.cleaned_data['efforts']
        project.status = self.cleaned_data['status']
        project.dead_line = self.cleaned_data['dead_line']
        # project.complete_per = self.cleaned_data['complete_per']
        project.description = self.cleaned_data['description']
        project.slug = slugify(str(self.cleaned_data['name']))
        project.save()
        devs = self.cleaned_data['developers']
        for d in devs:
            project.developers.add((d))
        mngs = self.cleaned_data['managers']
        for m in mngs:
            project.managers.add((m))

        if commit:
            project.save()

        return project


    def __init__(self, *args, **kwargs):
        super(ProjectRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'Project Name'
        self.fields['efforts'].widget.attrs['class'] = 'form-control'
        self.fields['efforts'].widget.attrs['placeholder'] = 'Efforts'
        self.fields['status'].widget.attrs['class'] = 'form-control'
        self.fields['status'].widget.attrs['placeholder'] = 'Status'
        self.fields['dead_line'].widget.attrs['class'] = 'form-control'
        self.fields['dead_line'].widget.attrs['placeholder'] = 'Dead Line, type a date'
        # self.fields['complete_per'].widget.attrs['class'] = 'form-control'
        # self.fields['complete_per'].widget.attrs['placeholder'] = 'Complete %'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['placeholder'] = 'Type here the project description...'
        self.fields['developers'].widget.attrs['class'] = 'form-control'
        self.fields['managers'].widget.attrs['class'] = 'form-control'
        
class ProjectRequestRegistrationForm(forms.ModelForm):
    name = forms.CharField(max_length=80)
    # slug = forms.SlugField('shortcut')
    dead_line = forms.DateField()
    # complete_per = forms.FloatField(min_value=0, max_value=100)
    description = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = ProjectRequest
        fields = '__all__'


    def save(self, commit=True):
        project = super(ProjectRequestRegistrationForm, self).save(commit=False)
        project.name = self.cleaned_data['name']
        project.dead_line = self.cleaned_data['dead_line']
        # project.complete_per = self.cleaned_data['complete_per']
        project.description = self.cleaned_data['description']
        project.slug = slugify(str(self.cleaned_data['name']))
        project.started = False
        project.save()

        return project


    def __init__(self, *args, **kwargs):
        super(ProjectRequestRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['class'] = 'form-control'
        self.fields['name'].widget.attrs['placeholder'] = 'Project Name'
        self.fields['dead_line'].widget.attrs['class'] = 'form-control'
        self.fields['dead_line'].widget.attrs['placeholder'] = 'Dead Line, type a date'
        # self.fields['complete_per'].widget.attrs['class'] = 'form-control'
        # self.fields['complete_per'].widget.attrs['placeholder'] = 'Complete %'
        self.fields['description'].widget.attrs['class'] = 'form-control'
        self.fields['description'].widget.attrs['placeholder'] = 'Type here the project description...'

TechBridge/projects/views.py
from django.shortcuts import render
from django.db.models import Avg
from projects.models import Project, ProjectRequest
from projects.models import Task
from projects.forms import TaskRegistrationForm
from projects.forms import ProjectRegistrationForm, ProjectRequestRegistrationForm
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from register.models import User

# Create your views here.
def projects(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('core:login'))
    projects = Project.objects.all()
    avg_projects = Project.objects.all().aggregate(Avg('complete_per'))['complete_per__avg']
    tasks = Task.objects.all()
    overdue_tasks = tasks.filter(due='2')
    context = {
        'avg_projects' : avg_projects,
        'projects' : projects,
        'tasks' : tasks,
        'overdue_tasks' : overdue_tasks,
    }
    return render(request, 'projects/projects.html', context)

# Create your views here.
def requests(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('core:login'))
    projects = ProjectRequest.objects.filter(started=False)
    context = {
        'projects' : projects,
    }
    return render(request, 'projects/requests.html', context)

def newTask(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('core:login'))
    if request.method == 'POST':
        form = TaskRegistrationForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            created = True
            context = {
                'created': created,
                'form': form,
            }
            return render(request, 'projects/new_task.html', context)
        else:
            return render(request, 'projects/new_task.html', context)
    else:
        form = TaskRegistrationForm()
        context = {
            'form': form,
        }
        return render(request,'projects/new_task.html', context)

def newProjectRequest(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('core:login'))
    if request.method == 'POST':
        form = ProjectRequestRegistrationForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            created = True
            form = ProjectRequestRegistrationForm()
            context = {
                'created': created,
                'form': form,
            }
            return render(request, 'projects/new_project_request.html', context)
        else:
            return render(request, 'projects/new_project_request.html', context)
    else:
        form = ProjectRequestRegistrationForm(initial={'requester':User.objects.get(id=request.user.id)})
        context = {
            'form': form,
        }
        return render(request,'projects/new_project_request.html', context)

def newProject(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('core:login'))
    if request.method == 'POST':
        form = ProjectRegistrationForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            created = True
            form = ProjectRegistrationForm()
            context = {
                'created': created,
                'form': form,
            }
            return render(request, 'projects/new_project.html', context)
        else:
            return render(request, 'projects/new_project.html', context)
    else:
        form = ProjectRegistrationForm(initial={'requester':request.user})

        context = {
            'form': form,
        }
        return render(request,'projects/new_project.html', context)

def newProjectFromRequest(request, id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('core:login'))
    if request.method == 'POST':
        form = ProjectRegistrationForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            created = True
            form = ProjectRegistrationForm()
            context = {
                'created': created,
                'form': form,
            }
            return render(request, 'projects/new_project.html', context)
        else:
            return render(request, 'projects/new_project.html', context)
    else:
        tmp = ProjectRequest.objects.filter(id=id)
        tmp.update(started = True)
        tmp = ProjectRequest.objects.get(id=id)
        form = ProjectRegistrationForm(initial={'name':tmp.name, 'description':tmp.description, 'dead_line':tmp.dead_line, 'requester': tmp.requester})
        # form.name = tmp.name
        # form.description = tmp.description
        # form.dead_line = tmp.dead_line

        context = {
            'form': form,
        }
        return render(request,'projects/new_project.html', context)

TechBridge/projects/templates/projects/new_project.html
{% extends 'core/base.html' %}
{% load static %}

{% block breadcrumb %}
        <li class="breadcrumb-item">Home</li>
        <li class="breadcrumb-item">Projects</li>
        <li class="breadcrumb-item active">New Project</li>
{% endblock breadcrumb%}





{% block content %}
<div class="container animated fadeIn">
        <div class="row justify-content-center">
            <div class="col-8">
                <div class="card-group">
                    <div class="card p-4 mb-5">
                        <div class="card-body">
                            {% if created %}
                              <div class="alert alert-success alert-dismissible fade show" role="alert">
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                  </button>
                                  Congratulations, your project was created!
                              </div>
                            {% endif %}
                                {% csrf_token %}
                                <h1>Projects</h1>
                                <p class="text-muted">Create your projects here</p>

                            <form action="" method="post">
                                {% csrf_token %}
                                <div hidden>
                                    {{form.requester}}
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-user"></i></span>
                                        </div>

                                        {{ form.name }}
                                        {% if form.name.errors %}
                                            <ol>
                                            {% for error in form.name.errors %}
                                                <li><strong>{{ error|escape }}</strong></li>
                                            {% endfor %}
                                            </ol>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-form-label">Developers. <i>Crtl+click for multiple selection</i></label>
                                    <div class="input-group">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-users"></i></span>
                                        </div>
                                        {{ form.developers }}
                                        {% if form.developers.errors %}
                                            <ol>
                                            {% for error in form.developers.errors %}
                                                <li><strong>{{ error|escape }}</strong></li>
                                            {% endfor %}
                                            </ol>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-form-label">Managers. <i>Crtl+click for multiple selection</i></label>
                                    <div class="input-group">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-users"></i></span>
                                        </div>
                                        {{ form.managers }}
                                        {% if form.managers.errors %}
                                            <ol>
                                            {% for error in form.managers.errors %}
                                                <li><strong>{{ error|escape }}</strong></li>
                                            {% endfor %}
                                            </ol>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-calculator"></i></span>
                                        </div>
                                        {{ form.efforts }}
                                        {% if form.efforts.errors %}
                                            <ol>
                                            {% for error in form.efforts.errors %}
                                                <li><strong>{{ error|escape }}</strong></li>
                                            {% endfor %}
                                            </ol>
                                        {% endif %}
                                    </div>
                                </div> 
                                 <div class="form-group">
                                    <label class="col-form-label">Status</label>
                                    <div class="input-group">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-circle"></i></span>
                                        </div>
                                        {{ form.status }}
                                        {% if form.status.errors %}
                                            <ol>
                                            {% for error in form.status.errors %}
                                                <li><strong>{{ error|escape }}</strong></li>
                                            {% endfor %}
                                            </ol>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-form-label">Finish By (Date)</label>
                                    <div class="input-group">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-calendar-alt"></i></span>
                                        </div>
                                        {{ form.dead_line }}
                                    </div>

                                    {% if form.dead_line.errors %}
                                            <ol>
                                            {% for error in form.dead_line.errors %}
                                                <li><strong>{{ error|escape }}</strong></li>
                                            {% endfor %}
                                            </ol>
                                        {% endif %}
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-percent"></i></span>
                                        </div>
                                        {{ form.complete_per }}
                                    </div>

                                    {% if form.complete_per.errors %}
                                            <ol>
                                            {% for error in form.complete_per.errors %}
                                                <li><strong>{{ error|escape }}</strong></li>
                                            {% endfor %}
                                            </ol>
                                        {% endif %}
                                </div> 
                                <div class="form-group">
                                    <label class="col-form-label">Description</label>
                                    <div class="input-group">
                                        <div class="input-group-append">
                                            <span class="input-group-text"><i class="fa fa-quote-left"></i></span>
                                        </div>
                                        {{ form.description }}
                                    </div>

                                    {% if form.description.errors %}
                                            <ol>
                                            {% for error in form.description.errors %}
                                                <li><strong>{{ error|escape }}</strong></li>
                                            {% endfor %}
                                            </ol>
                                        {% endif %}
                                </div>

                                <div class="">
                                    <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-dot-circle-o"></i> Submit</button>
                                    <button type="reset" class="btn btn-sm btn-danger"><i class="fa fa-ban"></i> Reset</button>
                                </div>
                            </form>
                            {{ form.errors }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

TechBridge/projects/templates/projects/requests.html
{% extends 'core/base.html' %}
{% load static %}


{% block breadcrumb %}
<li class="breadcrumb-item">Home</li>
<li class="breadcrumb-item">Projects</li>
<li class="breadcrumb-item active">Views</li>
{% endblock breadcrumb%}
{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <strong>{{ projects.count }} Pending Requests</strong>
        </div>
        <div class="card-body">
            <div class="row">
                {% for project in projects %}
                <div class="col-12 col-md-6 col-lg-4">
                <div class="card mx-2">
                    <div class="card-body">
                        <div class="h4 m-0">
                            {{ project.name }}
                        </div>
                        <div>Requested by <b>{{ project.requester.username }}</b></div>
                        <small class="text-muted">{{ project.description|truncatechars:60 }}</small>
                        {% if user.is_authenticated and user.is_member %}
                        <a href="{% url 'projects:new-project' project.id %}"><button class="btn btn-sm btn-success">Start Project</button></a>
                        {% endif %}
                        
                    </div>
                </div>
                </div>
                {% endfor %}
            </div>
            <br>
        </div>
    </div>
</div>
{% endblock %}